import type { Category } from "@/interfaces/category";

export const categoriesMock: Category[] = [
    {
        id: "cat-001",
        name: "Bebidas",
        description: "Bebidas frías y calientes",
        icon: "Coffee",
        color: "bg-amber-100 text-amber-700",
        productCount: 12,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "cat-002",
        name: "Carnes",
        description: "Carnes rojas y blancas",
        icon: "Beef",
        color: "bg-red-100 text-red-700",
        productCount: 8,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "cat-003",
        name: "Postres",
        description: "Dulces y postres",
        icon: "Cake",
        color: "bg-pink-100 text-pink-700",
        productCount: 15,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "cat-004",
        name: "Ensaladas",
        description: "Ensaladas frescas",
        icon: "Salad",
        color: "bg-green-100 text-green-700",
        productCount: 6,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "cat-005",
        name: "Hamburguesas",
        description: "Hamburguesas artesanales",
        icon: "Sandwich",
        color: "bg-orange-100 text-orange-700",
        productCount: 10,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "cat-006",
        name: "Pizzas",
        description: "Pizzas al horno",
        icon: "Pizza",
        color: "bg-yellow-100 text-yellow-700",
        productCount: 9,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const iconOptions = [
    { value: "Sandwich", label: "Hamburguesa" },
    { value: "Pizza", label: "Pizza" },
    { value: "Coffee", label: "Bebida" },
    { value: "Salad", label: "Ensalada" },
    { value: "Beef", label: "Carne" },
    { value: "Cake", label: "Postre" },
    { value: "Soup", label: "Sopa" },
    { value: "Cookie", label: "Galleta" },
    { value: "IceCream", label: "Helado" },
    { value: "Fish", label: "Pescado" },
    { value: "Egg", label: "Huevo" },
    { value: "Milk", label: "Lácteos" },
    { value: "Apple", label: "Frutas" },
    { value: "Carrot", label: "Verduras" },
    { value: "Wheat", label: "Panadería" },
    { value: "CupSoda", label: "Refrescos" },
];

export const colorOptions = [
    { value: "bg-red-100 text-red-700", label: "Rojo" },
    { value: "bg-orange-100 text-orange-700", label: "Naranja" },
    { value: "bg-amber-100 text-amber-700", label: "Ámbar" },
    { value: "bg-yellow-100 text-yellow-700", label: "Amarillo" },
    { value: "bg-green-100 text-green-700", label: "Verde" },
    { value: "bg-blue-100 text-blue-700", label: "Azul" },
    { value: "bg-purple-100 text-purple-700", label: "Morado" },
    { value: "bg-pink-100 text-pink-700", label: "Rosa" },
    { value: "bg-gray-100 text-gray-700", label: "Gris" },
];
